DELETE http://localhost:3000/api/v1/categories/2
###

POST http://localhost:3000/api/v1/categories/create
Content-Type: application/json

{   
    "category_name": "Foods",
    "description": "oishi",
    "slug": "foods"
}

